---
name: Renovate Changesets

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  renovate-changesets:
    if: github.actor == 'renovate[bot]' || github.actor == 'mrbro-bot[bot]'
    name: Create Renovate Changeset
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/renovate-changeset.yaml@276ebf70d364e345497612e6218bbdef8592df0c # v4.16.3
